"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](flamingo)\
$os\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$golang\
$python\
$docker_context\
$kubernetes\
$time\
[](blue)\
$line_break\
$character
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "fg:crust bg:pink"
truncation_symbol = ".../"
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
style = "fg:crust bg:maroon"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:crust bg:maroon"
format = '([\[$all_status$ahead_behind\] ]($style))'

[kubernetes]
disabled=false
style = "fg:crust bg:mauve"
format = '[ $symbol$context( \($namespace\)) ]($style)'
symbol = '󰠳 '

[time]
style = "fg:crust bg:blue"
disabled = false
time_format = "%R"
format = '[  $time ]($style)'

[username]
show_always = true
style_user = "fg:crust bg:flamingo"
style_root = "fg:crust bg:flamingo"
format = '[ $user ]($style)'
